version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo "Running checks..."
      - python manage.py check
      
  build:
    commands:
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput
      
  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - '**/*'