# Generated by Django 5.0.1 on 2025-11-24 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=50, verbose_name='Car Company')),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(verbose_name='Manufacturing Year')),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('van', 'Van')], default='sedan', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('mileage', models.IntegerField(help_text='Mileage in kilometers')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original purchase price', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Selling Price')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Price')),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('city', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=20)),
                ('image1', models.ImageField(default='default.jpg', upload_to='vehicles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
