# Generated by Django 5.0.1 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_booking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Debit/Credit Card')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
