# Generated by Django 5.0.1 on 2025-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_order_card_expiry_order_card_name_order_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
